version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
        name: build local
          command: |
            echo 'Test pipeline'
            echo 'This is the delivery pipeline'
      - run:
        name: second steps
          command: |
            ls -local
            echo 'the files in the repo'

