version: 2.1

executors:
  eln-executor:
    docker:
      - image: cimg/go:1.26.4-node
      - image: postgres:17
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
    resource_class: large

jobs:
  test:
    executor: eln-executor
    working_directory: ~/deltablot/eln.community
    steps:
      - checkout
      - run:
          name: Enable corepack
          command: corepack enable
      - run:
          name: Generate assets
          command: go generate ./src
      - run:
          name: Run tests
          command: go test -v ./src

workflows:
  test-workflow:
    jobs:
      - test
